{% set name = "irispy-lmsal" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/irispy-lmsal-{{ version }}.tar.gz
  sha256: b5b6c23e51cd4ebcf30f598a00e6509cd196c86428030202a1b5f1a0e0841f15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - dkist >=1.0.0
    - ndcube >=2.1.2
    - pandas >=1.3.3
    - scipy >=1.7.0
    - sunpy >=5.0.0
    - sunraster >=0.4.0
    - mpl_animators
    - matplotlib
    - packaging

test:
  imports:
    - irispy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://iris.lmsal.com/
  summary: Provides tools to read in and analyze data from the IRIS solar-observing satellite.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
