{% set name = "irispy-lmsal" %}
{% set version = "0.7.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7a6ea9f9ee8d9832819e0cdf1c791f17f83cdfaf9dfedf6d851ace9e06be1e2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - astropy >=7.2.0
    - dkist >=1.17.0
    - mpl_animators >=1.2.0
    - ndcube >=2.4.0
    - pandas >=3.0.0
    - scipy >=1.17.0
    - sunpy >=7.1.0
    - sunraster >=0.7.0

test:
  imports:
    - irispy
  commands:
    - pip check
    - pytest --pyargs irispy --remote-data=none
  requires:
    - pip
    - pooch
    - python {{ python_min }}
    - pytest-astropy
    - pytest-mpl

about:
  home: https://iris.lmsal.com/
  summary: Provides tools to read in and analyze data from the IRIS solar-observing satellite.
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
