{% set name = "irispy-lmsal" %}
{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8577bf7cd8e4dd2a584ce8197b16719a0f3d01164b1d19d72b278826b8b787aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - mpl_animators >=1.2.3
    - dkist >=1.15.0
    - ndcube >=2.3.0
    - pandas >=1.3.3
    - scipy >=1.7.0
    - sunpy >=7.0.0
    - sunraster >=0.6.1

test:
  imports:
    - irispy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://iris.lmsal.com/
  summary: Provides tools to read in and analyze data from the IRIS solar-observing satellite.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
