{% set name = "irispy-lmsal" %}
{% set version = "0.2.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 95004f72cd64b9eb8a0d96c4e7d179a36113f8112b62306c9d6588843e94b954

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - dkist >=1.0.0
    - ndcube >=2.3.0
    - pandas >=1.3.3
    - scipy >=1.7.0
    - sunpy >=6.0.0
    - sunraster >=0.4.0

test:
  imports:
    - irispy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://iris.lmsal.com/
  summary: Provides tools to read in and analyze data from the IRIS solar-observing satellite.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
