{% set name = "irispy-lmsal" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/irispy-lmsal-{{ version }}.tar.gz
  sha256: 7e4ebf00b7910a1d0bef0dc28b3a8d3db4645060738844b45b38648f6288a8d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.7
    - sunraster >=0.3.0,<0.4.0
    - sunpy >=3.1.0
    - scipy >=1.7.0
    - pandas >=1.3.3

test:
  imports:
    - irispy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://iris.lmsal.com/
  summary: Provides tools to read in and analyze data from the IRIS solar-observing satellite.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - nabobalis
